// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-A0ukLgJVXsMDNTyQfNFPpQ0vgM5iHd4',
    appId: '1:79025728776:web:2449e119a9d74b3b4090bd',
    messagingSenderId: '79025728776',
    projectId: 'lovabledatingapps',
    authDomain: 'lovabledatingapps.firebaseapp.com',
    storageBucket: 'lovabledatingapps.firebasestorage.app',
    measurementId: 'G-S0SJL72164',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFt5RtgI8itoTl6JSvmcxfloOa9URubmk',
    appId: '1:79025728776:android:d11cae1427f860504090bd',
    messagingSenderId: '79025728776',
    projectId: 'lovabledatingapps',
    storageBucket: 'lovabledatingapps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0RC0KAtcbh3iz0bKfhuPqa53Q6o35RBI',
    appId: '1:79025728776:ios:49b3bd229d9c0bc84090bd',
    messagingSenderId: '79025728776',
    projectId: 'lovabledatingapps',
    storageBucket: 'lovabledatingapps.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0RC0KAtcbh3iz0bKfhuPqa53Q6o35RBI',
    appId: '1:79025728776:ios:49b3bd229d9c0bc84090bd',
    messagingSenderId: '79025728776',
    projectId: 'lovabledatingapps',
    storageBucket: 'lovabledatingapps.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-A0ukLgJVXsMDNTyQfNFPpQ0vgM5iHd4',
    appId: '1:79025728776:web:361bd258de0937ce4090bd',
    messagingSenderId: '79025728776',
    projectId: 'lovabledatingapps',
    authDomain: 'lovabledatingapps.firebaseapp.com',
    storageBucket: 'lovabledatingapps.firebasestorage.app',
    measurementId: 'G-6FGWZJMJCK',
  );

}